name: depth-jitter
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.31
  - curl=8.11.1
  - expat=2.6.4
  - gettext=0.21.0
  - git=2.45.2
  - icu=73.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libcurl=8.11.1
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.57.0
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - ncurses=6.4
  - openssl=3.0.15
  - pcre2=10.42
  - perl=5.38.2
  - pip=24.2
  - python=3.11.11
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - absl-py==2.1.0
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.11.11
    - aiosignal==1.3.2
    - alembic==1.14.1
    - annotated-types==0.7.0
    - asttokens==3.0.0
    - attrs==24.3.0
    - certifi==2024.12.14
    - charset-normalizer==3.4.1
    - click==8.1.8
    - colorlog==6.9.0
    - comm==0.2.2
    - contourpy==1.3.1
    - cycler==0.12.1
    - debugpy==1.8.11
    - decorator==5.1.1
    - docker-pycreds==0.4.0
    - einops==0.8.0
    - executing==2.1.0
    - filelock==3.16.1
    - fonttools==4.55.3
    - frozenlist==1.5.0
    - fsspec==2024.12.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - greenlet==3.1.1
    - grpcio==1.70.0
    - huggingface-hub==0.27.0
    - idna==3.10
    - ipykernel==6.29.5
    - ipython==8.31.0
    - jedi==0.19.2
    - jinja2==3.1.5
    - joblib==1.4.2
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - kiwisolver==1.4.8
    - lightning==2.5.0.post0
    - lightning-utilities==0.11.9
    - mako==1.3.8
    - markdown==3.7
    - markupsafe==3.0.2
    - matplotlib==3.10.0
    - matplotlib-inline==0.1.7
    - mpmath==1.3.0
    - multidict==6.1.0
    - nest-asyncio==1.6.0
    - networkx==3.4.2
    - numpy==2.2.1
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - opencv-python==4.10.0.84
    - optuna==4.2.0
    - optuna-integration==4.2.1
    - packaging==24.2
    - pandas==2.2.3
    - parso==0.8.4
    - pexpect==4.9.0
    - pillow==11.0.0
    - platformdirs==4.3.6
    - positional-encodings==6.0.3
    - prompt-toolkit==3.0.48
    - propcache==0.2.1
    - protobuf==5.29.2
    - psutil==6.1.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pycocotools==2.0.8
    - pydantic==2.10.4
    - pydantic-core==2.27.2
    - pygments==2.18.0
    - pyparsing==3.2.0
    - python-dateutil==2.9.0.post0
    - pytorch-lightning==2.5.0.post0
    - pytz==2024.2
    - pyyaml==6.0.2
    - pyzmq==26.2.0
    - randaugment==1.0.2
    - regex==2024.11.6
    - requests==2.32.3
    - safetensors==0.4.5
    - scikit-learn==1.6.0
    - scipy==1.14.1
    - seaborn==0.13.2
    - sentry-sdk==2.19.2
    - setproctitle==1.3.4
    - six==1.17.0
    - smmap==5.0.1
    - sqlalchemy==2.0.37
    - stack-data==0.6.3
    - sympy==1.13.1
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - threadpoolctl==3.5.0
    - timm==1.0.12
    - tokenizers==0.21.0
    - torch==2.5.1
    - torchmetrics==1.6.1
    - torchvision==0.20.1
    - tornado==6.4.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - transformers==4.47.1
    - triton==3.1.0
    - typing-extensions==4.12.2
    - tzdata==2024.2
    - urllib3==2.3.0
    - wandb==0.19.1
    - wcwidth==0.2.13
    - werkzeug==3.1.3
    - yarl==1.18.3
